[theme]
primaryColor = "#00BFFF"  # Нежный небесно-голубой для кнопок
backgroundColor = "#1C1C1C"  # Глубокий антрацит для фона
secondaryBackgroundColor = "#2E2E2E"  # Умеренный тёмно-серый для боковой панели
textColor = "#DCDCDC"  # Светло-серый для текста
