[theme]
primaryColor = "#1E90FF"  # Нежный синий для кнопок
backgroundColor = "#2B2B2B"  # Тёмно-серый для фона
secondaryBackgroundColor = "#383838"  # Немного светлее для боковой панели
textColor = "#E0E0E0"  # Светлый текст
font = "sans serif"  # Шрифт текста
